#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-jmespath
Version  : 0.9.3
Release  : 34
URL      : http://pypi.debian.net/jmespath/jmespath-0.9.3.tar.gz
Source0  : http://pypi.debian.net/jmespath/jmespath-0.9.3.tar.gz
Summary  : JSON Matching Expressions
Group    : Development/Tools
License  : MIT
Requires: deprecated-jmespath-bin = %{version}-%{release}
Requires: deprecated-jmespath-license = %{version}-%{release}
Requires: deprecated-jmespath-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3

%description
JMESPath
========
.. image:: https://badges.gitter.im/Join Chat.svg
:target: https://gitter.im/jmespath/chat

%package bin
Summary: bin components for the deprecated-jmespath package.
Group: Binaries
Requires: deprecated-jmespath-license = %{version}-%{release}

%description bin
bin components for the deprecated-jmespath package.


%package legacypython
Summary: legacypython components for the deprecated-jmespath package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-jmespath package.


%package license
Summary: license components for the deprecated-jmespath package.
Group: Default

%description license
license components for the deprecated-jmespath package.


%package python
Summary: python components for the deprecated-jmespath package.
Group: Default

%description python
python components for the deprecated-jmespath package.


%prep
%setup -q -n jmespath-0.9.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554321648
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-jmespath
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-jmespath/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jp.py

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-jmespath/LICENSE.txt

%files python
%defattr(-,root,root,-)
